apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-task
  labels:
    app: api-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api-deployment
          image: stratcastor/nodeapp:latest
          ports:
            - containerPort: 8080       
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-deployment
spec:
  type: ClusterIP
  selector:
    app: api-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080